version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - celery_worker
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # Only needed if you want to use local MongoDB. Remove if using Atlas.

  celery_worker:
    build: .
    command: celery -A app.tasks.process_tasks worker --loglevel=info --pool=solo
    depends_on:
      - app
    env_file:
      - .env

  kafka_consumer:
    build: .
    command: python -m app.utils.kafka_consumer
    depends_on:
      - app
    env_file:
      - .env

volumes:
  mongo_data:
